//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_Conexion_PCH.ServicePCH {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO", ConfigurationName="ServicePCH.PCH_MAYOREOPortType")]
    public interface PCH_MAYOREOPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://serviciosmayoristas.pchmayoreo.com/) del mensaje ObtenerListaArticulosRequest no coincide con el valor predeterminado (http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO)
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/ObtenerListaArticulos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidadPrecio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctInventario))]
        test_Conexion_PCH.ServicePCH.ObtenerListaArticulosResponse ObtenerListaArticulos(test_Conexion_PCH.ServicePCH.ObtenerListaArticulosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/ObtenerListaArticulos", ReplyAction="*")]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerListaArticulosResponse> ObtenerListaArticulosAsync(test_Conexion_PCH.ServicePCH.ObtenerListaArticulosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://serviciosmayoristas.pchmayoreo.com/) del mensaje ObtenerArticuloRequest no coincide con el valor predeterminado (http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO)
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/ObtenerArticulo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidadPrecio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctInventario))]
        test_Conexion_PCH.ServicePCH.ObtenerArticuloResponse ObtenerArticulo(test_Conexion_PCH.ServicePCH.ObtenerArticuloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/ObtenerArticulo", ReplyAction="*")]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerArticuloResponse> ObtenerArticuloAsync(test_Conexion_PCH.ServicePCH.ObtenerArticuloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://serviciosmayoristas.pchmayoreo.com/) del mensaje ObtenerParidadRequest no coincide con el valor predeterminado (http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO)
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/ObtenerParidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidadPrecio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctInventario))]
        test_Conexion_PCH.ServicePCH.ObtenerParidadResponse ObtenerParidad(test_Conexion_PCH.ServicePCH.ObtenerParidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/ObtenerParidad", ReplyAction="*")]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerParidadResponse> ObtenerParidadAsync(test_Conexion_PCH.ServicePCH.ObtenerParidadRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://serviciosmayoristas.pchmayoreo.com/) del mensaje GenerarRemisionRequest no coincide con el valor predeterminado (http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO)
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/GenerarRemision", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidadPrecio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctInventario))]
        test_Conexion_PCH.ServicePCH.GenerarRemisionResponse GenerarRemision(test_Conexion_PCH.ServicePCH.GenerarRemisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/GenerarRemision", ReplyAction="*")]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.GenerarRemisionResponse> GenerarRemisionAsync(test_Conexion_PCH.ServicePCH.GenerarRemisionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://serviciosmayoristas.pchmayoreo.com/) del mensaje ObtenerFacturaPorOcRequest no coincide con el valor predeterminado (http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO)
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/ObtenerFacturaPorOc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidadPrecio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctInventario))]
        test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcResponse ObtenerFacturaPorOc(test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/ObtenerFacturaPorOc", ReplyAction="*")]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcResponse> ObtenerFacturaPorOcAsync(test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://serviciosmayoristas.pchmayoreo.com/) del mensaje GenerarFacturaRequest no coincide con el valor predeterminado (http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO)
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/GenerarFactura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidadPrecio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctInventario))]
        test_Conexion_PCH.ServicePCH.GenerarFacturaResponse GenerarFactura(test_Conexion_PCH.ServicePCH.GenerarFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/GenerarFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.GenerarFacturaResponse> GenerarFacturaAsync(test_Conexion_PCH.ServicePCH.GenerarFacturaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://serviciosmayoristas.pchmayoreo.com/) del mensaje GenerarRemisionConPrecioRequest no coincide con el valor predeterminado (http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO)
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/GenerarRemisionConPrecio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidadPrecio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctInventario))]
        test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioResponse GenerarRemisionConPrecio(test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/GenerarRemisionConPrecio", ReplyAction="*")]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioResponse> GenerarRemisionConPrecioAsync(test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (http://serviciosmayoristas.pchmayoreo.com/) del mensaje ServicioAprobatorioRequest no coincide con el valor predeterminado (http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO)
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/ServicioAprobatorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidadPrecio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctArticuloCantidad))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ctInventario))]
        test_Conexion_PCH.ServicePCH.ServicioAprobatorioResponse ServicioAprobatorio(test_Conexion_PCH.ServicePCH.ServicioAprobatorioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosmayoristas.pchmayoreo.com/servidor.php/ServicioAprobatorio", ReplyAction="*")]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ServicioAprobatorioResponse> ServicioAprobatorioAsync(test_Conexion_PCH.ServicePCH.ServicioAprobatorioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctCamposObtenerListaArticulos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estatusField;
        
        private string mensajeField;
        
        private ctArticulo[] datosField;
        
        /// <remarks/>
        public bool estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public ctArticulo[] datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
                this.RaisePropertyChanged("datos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctArticulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        private string descripcionField;
        
        private string skuFabricanteField;
        
        private string seccionField;
        
        private string lineaField;
        
        private string marcaField;
        
        private string serieField;
        
        private float precioField;
        
        private float pesoField;
        
        private float altoField;
        
        private float largoField;
        
        private float anchoField;
        
        private string monedaField;
        
        private string upcField;
        
        private ctInventario[] inventarioField;
        
        private int id_marcaField;
        
        private int id_seccionField;
        
        private int id_lineaField;
        
        private int id_serieField;
        
        /// <remarks/>
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("sku");
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        public string skuFabricante {
            get {
                return this.skuFabricanteField;
            }
            set {
                this.skuFabricanteField = value;
                this.RaisePropertyChanged("skuFabricante");
            }
        }
        
        /// <remarks/>
        public string seccion {
            get {
                return this.seccionField;
            }
            set {
                this.seccionField = value;
                this.RaisePropertyChanged("seccion");
            }
        }
        
        /// <remarks/>
        public string linea {
            get {
                return this.lineaField;
            }
            set {
                this.lineaField = value;
                this.RaisePropertyChanged("linea");
            }
        }
        
        /// <remarks/>
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        public float precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        public float peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
                this.RaisePropertyChanged("peso");
            }
        }
        
        /// <remarks/>
        public float alto {
            get {
                return this.altoField;
            }
            set {
                this.altoField = value;
                this.RaisePropertyChanged("alto");
            }
        }
        
        /// <remarks/>
        public float largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
                this.RaisePropertyChanged("largo");
            }
        }
        
        /// <remarks/>
        public float ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
                this.RaisePropertyChanged("ancho");
            }
        }
        
        /// <remarks/>
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("moneda");
            }
        }
        
        /// <remarks/>
        public string upc {
            get {
                return this.upcField;
            }
            set {
                this.upcField = value;
                this.RaisePropertyChanged("upc");
            }
        }
        
        /// <remarks/>
        public ctInventario[] inventario {
            get {
                return this.inventarioField;
            }
            set {
                this.inventarioField = value;
                this.RaisePropertyChanged("inventario");
            }
        }
        
        /// <remarks/>
        public int id_marca {
            get {
                return this.id_marcaField;
            }
            set {
                this.id_marcaField = value;
                this.RaisePropertyChanged("id_marca");
            }
        }
        
        /// <remarks/>
        public int id_seccion {
            get {
                return this.id_seccionField;
            }
            set {
                this.id_seccionField = value;
                this.RaisePropertyChanged("id_seccion");
            }
        }
        
        /// <remarks/>
        public int id_linea {
            get {
                return this.id_lineaField;
            }
            set {
                this.id_lineaField = value;
                this.RaisePropertyChanged("id_linea");
            }
        }
        
        /// <remarks/>
        public int id_serie {
            get {
                return this.id_serieField;
            }
            set {
                this.id_serieField = value;
                this.RaisePropertyChanged("id_serie");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctInventario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int almacenField;
        
        private int existenciaField;
        
        /// <remarks/>
        public int almacen {
            get {
                return this.almacenField;
            }
            set {
                this.almacenField = value;
                this.RaisePropertyChanged("almacen");
            }
        }
        
        /// <remarks/>
        public int existencia {
            get {
                return this.existenciaField;
            }
            set {
                this.existenciaField = value;
                this.RaisePropertyChanged("existencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctRespuestaAprobatorio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strRespuestaField;
        
        /// <remarks/>
        public string strRespuesta {
            get {
                return this.strRespuestaField;
            }
            set {
                this.strRespuestaField = value;
                this.RaisePropertyChanged("strRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctCamposServicioAprobatorio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estatusField;
        
        private string mensajeField;
        
        private ctRespuestaAprobatorio datosField;
        
        /// <remarks/>
        public bool estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public ctRespuestaAprobatorio datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
                this.RaisePropertyChanged("datos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctArticuloPrecio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strSkuField;
        
        private float fPrecioField;
        
        /// <remarks/>
        public string strSku {
            get {
                return this.strSkuField;
            }
            set {
                this.strSkuField = value;
                this.RaisePropertyChanged("strSku");
            }
        }
        
        /// <remarks/>
        public float fPrecio {
            get {
                return this.fPrecioField;
            }
            set {
                this.fPrecioField = value;
                this.RaisePropertyChanged("fPrecio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctArticuloCantidadPrecio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strSkuField;
        
        private int iCantidadField;
        
        private float fPrecioField;
        
        /// <remarks/>
        public string strSku {
            get {
                return this.strSkuField;
            }
            set {
                this.strSkuField = value;
                this.RaisePropertyChanged("strSku");
            }
        }
        
        /// <remarks/>
        public int iCantidad {
            get {
                return this.iCantidadField;
            }
            set {
                this.iCantidadField = value;
                this.RaisePropertyChanged("iCantidad");
            }
        }
        
        /// <remarks/>
        public float fPrecio {
            get {
                return this.fPrecioField;
            }
            set {
                this.fPrecioField = value;
                this.RaisePropertyChanged("fPrecio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctFactura : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int iFacturaField;
        
        private string strSucursalField;
        
        /// <remarks/>
        public int iFactura {
            get {
                return this.iFacturaField;
            }
            set {
                this.iFacturaField = value;
                this.RaisePropertyChanged("iFactura");
            }
        }
        
        /// <remarks/>
        public string strSucursal {
            get {
                return this.strSucursalField;
            }
            set {
                this.strSucursalField = value;
                this.RaisePropertyChanged("strSucursal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctCamposFactura : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estatusField;
        
        private string mensajeField;
        
        private ctFactura datosField;
        
        /// <remarks/>
        public bool estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public ctFactura datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
                this.RaisePropertyChanged("datos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctFacturaPorOc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int iFacturaField;
        
        private string strSucursalField;
        
        private string dtFechaField;
        
        private float fTotalField;
        
        private string strPdfField;
        
        /// <remarks/>
        public int iFactura {
            get {
                return this.iFacturaField;
            }
            set {
                this.iFacturaField = value;
                this.RaisePropertyChanged("iFactura");
            }
        }
        
        /// <remarks/>
        public string strSucursal {
            get {
                return this.strSucursalField;
            }
            set {
                this.strSucursalField = value;
                this.RaisePropertyChanged("strSucursal");
            }
        }
        
        /// <remarks/>
        public string dtFecha {
            get {
                return this.dtFechaField;
            }
            set {
                this.dtFechaField = value;
                this.RaisePropertyChanged("dtFecha");
            }
        }
        
        /// <remarks/>
        public float fTotal {
            get {
                return this.fTotalField;
            }
            set {
                this.fTotalField = value;
                this.RaisePropertyChanged("fTotal");
            }
        }
        
        /// <remarks/>
        public string strPdf {
            get {
                return this.strPdfField;
            }
            set {
                this.strPdfField = value;
                this.RaisePropertyChanged("strPdf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctCamposFacturaPorOc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estatusField;
        
        private string mensajeField;
        
        private ctFacturaPorOc datosField;
        
        /// <remarks/>
        public bool estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public ctFacturaPorOc datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
                this.RaisePropertyChanged("datos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctCamposGenerarRemision : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estatusField;
        
        private string mensajeField;
        
        private int datosField;
        
        /// <remarks/>
        public bool estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public int datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
                this.RaisePropertyChanged("datos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctArticuloCantidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strSkuField;
        
        private int iCantidadField;
        
        /// <remarks/>
        public string strSku {
            get {
                return this.strSkuField;
            }
            set {
                this.strSkuField = value;
                this.RaisePropertyChanged("strSku");
            }
        }
        
        /// <remarks/>
        public int iCantidad {
            get {
                return this.iCantidadField;
            }
            set {
                this.iCantidadField = value;
                this.RaisePropertyChanged("iCantidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctCamposObtenerParidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estatusField;
        
        private string mensajeField;
        
        private float datosField;
        
        /// <remarks/>
        public bool estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public float datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
                this.RaisePropertyChanged("datos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://serviciosmayoristas.pchmayoreo.com/soap/PCH_MAYOREO")]
    public partial class ctCamposObtenerArticulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estatusField;
        
        private string mensajeField;
        
        private ctArticulo datosField;
        
        /// <remarks/>
        public bool estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public ctArticulo datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
                this.RaisePropertyChanged("datos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaArticulos", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class ObtenerListaArticulosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string llave;
        
        public ObtenerListaArticulosRequest() {
        }
        
        public ObtenerListaArticulosRequest(int cliente, string llave) {
            this.cliente = cliente;
            this.llave = llave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerListaArticulosResponse", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class ObtenerListaArticulosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public test_Conexion_PCH.ServicePCH.ctCamposObtenerListaArticulos resultado;
        
        public ObtenerListaArticulosResponse() {
        }
        
        public ObtenerListaArticulosResponse(test_Conexion_PCH.ServicePCH.ctCamposObtenerListaArticulos resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerArticulo", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class ObtenerArticuloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string llave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sku;
        
        public ObtenerArticuloRequest() {
        }
        
        public ObtenerArticuloRequest(int cliente, string llave, string sku) {
            this.cliente = cliente;
            this.llave = llave;
            this.sku = sku;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerArticuloResponse", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class ObtenerArticuloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public test_Conexion_PCH.ServicePCH.ctCamposObtenerArticulo resultado;
        
        public ObtenerArticuloResponse() {
        }
        
        public ObtenerArticuloResponse(test_Conexion_PCH.ServicePCH.ctCamposObtenerArticulo resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerParidad", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class ObtenerParidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string llave;
        
        public ObtenerParidadRequest() {
        }
        
        public ObtenerParidadRequest(int cliente, string llave) {
            this.cliente = cliente;
            this.llave = llave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerParidadResponse", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class ObtenerParidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public test_Conexion_PCH.ServicePCH.ctCamposObtenerParidad resultado;
        
        public ObtenerParidadResponse() {
        }
        
        public ObtenerParidadResponse(test_Conexion_PCH.ServicePCH.ctCamposObtenerParidad resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarRemision", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class GenerarRemisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string llave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int almacen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string moneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public test_Conexion_PCH.ServicePCH.ctArticuloCantidad[] articulos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string incluirSeguro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string folioOC;
        
        public GenerarRemisionRequest() {
        }
        
        public GenerarRemisionRequest(int cliente, string llave, int almacen, string moneda, test_Conexion_PCH.ServicePCH.ctArticuloCantidad[] articulos, string incluirSeguro, string folioOC) {
            this.cliente = cliente;
            this.llave = llave;
            this.almacen = almacen;
            this.moneda = moneda;
            this.articulos = articulos;
            this.incluirSeguro = incluirSeguro;
            this.folioOC = folioOC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarRemisionResponse", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class GenerarRemisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public test_Conexion_PCH.ServicePCH.ctCamposGenerarRemision resultado;
        
        public GenerarRemisionResponse() {
        }
        
        public GenerarRemisionResponse(test_Conexion_PCH.ServicePCH.ctCamposGenerarRemision resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerFacturaPorOc", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class ObtenerFacturaPorOcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string llave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string oc;
        
        public ObtenerFacturaPorOcRequest() {
        }
        
        public ObtenerFacturaPorOcRequest(int cliente, string llave, string oc) {
            this.cliente = cliente;
            this.llave = llave;
            this.oc = oc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerFacturaPorOcResponse", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class ObtenerFacturaPorOcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public test_Conexion_PCH.ServicePCH.ctCamposFacturaPorOc resultado;
        
        public ObtenerFacturaPorOcResponse() {
        }
        
        public ObtenerFacturaPorOcResponse(test_Conexion_PCH.ServicePCH.ctCamposFacturaPorOc resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarFactura", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class GenerarFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string llave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int remision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string calle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string numero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string colonia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string ciudad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string cp;
        
        public GenerarFacturaRequest() {
        }
        
        public GenerarFacturaRequest(int cliente, string llave, int remision, string nombre, string calle, string numero, string colonia, string ciudad, string estado, string cp) {
            this.cliente = cliente;
            this.llave = llave;
            this.remision = remision;
            this.nombre = nombre;
            this.calle = calle;
            this.numero = numero;
            this.colonia = colonia;
            this.ciudad = ciudad;
            this.estado = estado;
            this.cp = cp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarFacturaResponse", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class GenerarFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public test_Conexion_PCH.ServicePCH.ctCamposFactura resultado;
        
        public GenerarFacturaResponse() {
        }
        
        public GenerarFacturaResponse(test_Conexion_PCH.ServicePCH.ctCamposFactura resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarRemisionConPrecio", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class GenerarRemisionConPrecioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string llave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int almacen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string moneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public test_Conexion_PCH.ServicePCH.ctArticuloCantidadPrecio[] articulos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string incluirSeguro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string folioOC;
        
        public GenerarRemisionConPrecioRequest() {
        }
        
        public GenerarRemisionConPrecioRequest(int cliente, string llave, int almacen, string moneda, test_Conexion_PCH.ServicePCH.ctArticuloCantidadPrecio[] articulos, string incluirSeguro, string folioOC) {
            this.cliente = cliente;
            this.llave = llave;
            this.almacen = almacen;
            this.moneda = moneda;
            this.articulos = articulos;
            this.incluirSeguro = incluirSeguro;
            this.folioOC = folioOC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarRemisionConPrecioResponse", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class GenerarRemisionConPrecioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public test_Conexion_PCH.ServicePCH.ctCamposGenerarRemision resultado;
        
        public GenerarRemisionConPrecioResponse() {
        }
        
        public GenerarRemisionConPrecioResponse(test_Conexion_PCH.ServicePCH.ctCamposGenerarRemision resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServicioAprobatorio", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class ServicioAprobatorioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string llave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public test_Conexion_PCH.ServicePCH.ctArticuloPrecio articulo;
        
        public ServicioAprobatorioRequest() {
        }
        
        public ServicioAprobatorioRequest(int cliente, string llave, test_Conexion_PCH.ServicePCH.ctArticuloPrecio articulo) {
            this.cliente = cliente;
            this.llave = llave;
            this.articulo = articulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServicioAprobatorioResponse", WrapperNamespace="http://serviciosmayoristas.pchmayoreo.com/", IsWrapped=true)]
    public partial class ServicioAprobatorioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public test_Conexion_PCH.ServicePCH.ctCamposServicioAprobatorio resultado;
        
        public ServicioAprobatorioResponse() {
        }
        
        public ServicioAprobatorioResponse(test_Conexion_PCH.ServicePCH.ctCamposServicioAprobatorio resultado) {
            this.resultado = resultado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PCH_MAYOREOPortTypeChannel : test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PCH_MAYOREOPortTypeClient : System.ServiceModel.ClientBase<test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType>, test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType {
        
        public PCH_MAYOREOPortTypeClient() {
        }
        
        public PCH_MAYOREOPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PCH_MAYOREOPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PCH_MAYOREOPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PCH_MAYOREOPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_Conexion_PCH.ServicePCH.ObtenerListaArticulosResponse test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.ObtenerListaArticulos(test_Conexion_PCH.ServicePCH.ObtenerListaArticulosRequest request) {
            return base.Channel.ObtenerListaArticulos(request);
        }
        
        public test_Conexion_PCH.ServicePCH.ctCamposObtenerListaArticulos ObtenerListaArticulos(int cliente, string llave) {
            test_Conexion_PCH.ServicePCH.ObtenerListaArticulosRequest inValue = new test_Conexion_PCH.ServicePCH.ObtenerListaArticulosRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            test_Conexion_PCH.ServicePCH.ObtenerListaArticulosResponse retVal = ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).ObtenerListaArticulos(inValue);
            return retVal.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerListaArticulosResponse> test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.ObtenerListaArticulosAsync(test_Conexion_PCH.ServicePCH.ObtenerListaArticulosRequest request) {
            return base.Channel.ObtenerListaArticulosAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerListaArticulosResponse> ObtenerListaArticulosAsync(int cliente, string llave) {
            test_Conexion_PCH.ServicePCH.ObtenerListaArticulosRequest inValue = new test_Conexion_PCH.ServicePCH.ObtenerListaArticulosRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            return ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).ObtenerListaArticulosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_Conexion_PCH.ServicePCH.ObtenerArticuloResponse test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.ObtenerArticulo(test_Conexion_PCH.ServicePCH.ObtenerArticuloRequest request) {
            return base.Channel.ObtenerArticulo(request);
        }
        
        public test_Conexion_PCH.ServicePCH.ctCamposObtenerArticulo ObtenerArticulo(int cliente, string llave, string sku) {
            test_Conexion_PCH.ServicePCH.ObtenerArticuloRequest inValue = new test_Conexion_PCH.ServicePCH.ObtenerArticuloRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.sku = sku;
            test_Conexion_PCH.ServicePCH.ObtenerArticuloResponse retVal = ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).ObtenerArticulo(inValue);
            return retVal.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerArticuloResponse> test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.ObtenerArticuloAsync(test_Conexion_PCH.ServicePCH.ObtenerArticuloRequest request) {
            return base.Channel.ObtenerArticuloAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerArticuloResponse> ObtenerArticuloAsync(int cliente, string llave, string sku) {
            test_Conexion_PCH.ServicePCH.ObtenerArticuloRequest inValue = new test_Conexion_PCH.ServicePCH.ObtenerArticuloRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.sku = sku;
            return ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).ObtenerArticuloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_Conexion_PCH.ServicePCH.ObtenerParidadResponse test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.ObtenerParidad(test_Conexion_PCH.ServicePCH.ObtenerParidadRequest request) {
            return base.Channel.ObtenerParidad(request);
        }
        
        public test_Conexion_PCH.ServicePCH.ctCamposObtenerParidad ObtenerParidad(int cliente, string llave) {
            test_Conexion_PCH.ServicePCH.ObtenerParidadRequest inValue = new test_Conexion_PCH.ServicePCH.ObtenerParidadRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            test_Conexion_PCH.ServicePCH.ObtenerParidadResponse retVal = ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).ObtenerParidad(inValue);
            return retVal.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerParidadResponse> test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.ObtenerParidadAsync(test_Conexion_PCH.ServicePCH.ObtenerParidadRequest request) {
            return base.Channel.ObtenerParidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerParidadResponse> ObtenerParidadAsync(int cliente, string llave) {
            test_Conexion_PCH.ServicePCH.ObtenerParidadRequest inValue = new test_Conexion_PCH.ServicePCH.ObtenerParidadRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            return ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).ObtenerParidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_Conexion_PCH.ServicePCH.GenerarRemisionResponse test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.GenerarRemision(test_Conexion_PCH.ServicePCH.GenerarRemisionRequest request) {
            return base.Channel.GenerarRemision(request);
        }
        
        public test_Conexion_PCH.ServicePCH.ctCamposGenerarRemision GenerarRemision(int cliente, string llave, int almacen, string moneda, test_Conexion_PCH.ServicePCH.ctArticuloCantidad[] articulos, string incluirSeguro, string folioOC) {
            test_Conexion_PCH.ServicePCH.GenerarRemisionRequest inValue = new test_Conexion_PCH.ServicePCH.GenerarRemisionRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.almacen = almacen;
            inValue.moneda = moneda;
            inValue.articulos = articulos;
            inValue.incluirSeguro = incluirSeguro;
            inValue.folioOC = folioOC;
            test_Conexion_PCH.ServicePCH.GenerarRemisionResponse retVal = ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).GenerarRemision(inValue);
            return retVal.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.GenerarRemisionResponse> test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.GenerarRemisionAsync(test_Conexion_PCH.ServicePCH.GenerarRemisionRequest request) {
            return base.Channel.GenerarRemisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.GenerarRemisionResponse> GenerarRemisionAsync(int cliente, string llave, int almacen, string moneda, test_Conexion_PCH.ServicePCH.ctArticuloCantidad[] articulos, string incluirSeguro, string folioOC) {
            test_Conexion_PCH.ServicePCH.GenerarRemisionRequest inValue = new test_Conexion_PCH.ServicePCH.GenerarRemisionRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.almacen = almacen;
            inValue.moneda = moneda;
            inValue.articulos = articulos;
            inValue.incluirSeguro = incluirSeguro;
            inValue.folioOC = folioOC;
            return ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).GenerarRemisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcResponse test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.ObtenerFacturaPorOc(test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcRequest request) {
            return base.Channel.ObtenerFacturaPorOc(request);
        }
        
        public test_Conexion_PCH.ServicePCH.ctCamposFacturaPorOc ObtenerFacturaPorOc(int cliente, string llave, string oc) {
            test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcRequest inValue = new test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.oc = oc;
            test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcResponse retVal = ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).ObtenerFacturaPorOc(inValue);
            return retVal.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcResponse> test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.ObtenerFacturaPorOcAsync(test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcRequest request) {
            return base.Channel.ObtenerFacturaPorOcAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcResponse> ObtenerFacturaPorOcAsync(int cliente, string llave, string oc) {
            test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcRequest inValue = new test_Conexion_PCH.ServicePCH.ObtenerFacturaPorOcRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.oc = oc;
            return ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).ObtenerFacturaPorOcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_Conexion_PCH.ServicePCH.GenerarFacturaResponse test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.GenerarFactura(test_Conexion_PCH.ServicePCH.GenerarFacturaRequest request) {
            return base.Channel.GenerarFactura(request);
        }
        
        public test_Conexion_PCH.ServicePCH.ctCamposFactura GenerarFactura(int cliente, string llave, int remision, string nombre, string calle, string numero, string colonia, string ciudad, string estado, string cp) {
            test_Conexion_PCH.ServicePCH.GenerarFacturaRequest inValue = new test_Conexion_PCH.ServicePCH.GenerarFacturaRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.remision = remision;
            inValue.nombre = nombre;
            inValue.calle = calle;
            inValue.numero = numero;
            inValue.colonia = colonia;
            inValue.ciudad = ciudad;
            inValue.estado = estado;
            inValue.cp = cp;
            test_Conexion_PCH.ServicePCH.GenerarFacturaResponse retVal = ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).GenerarFactura(inValue);
            return retVal.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.GenerarFacturaResponse> test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.GenerarFacturaAsync(test_Conexion_PCH.ServicePCH.GenerarFacturaRequest request) {
            return base.Channel.GenerarFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.GenerarFacturaResponse> GenerarFacturaAsync(int cliente, string llave, int remision, string nombre, string calle, string numero, string colonia, string ciudad, string estado, string cp) {
            test_Conexion_PCH.ServicePCH.GenerarFacturaRequest inValue = new test_Conexion_PCH.ServicePCH.GenerarFacturaRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.remision = remision;
            inValue.nombre = nombre;
            inValue.calle = calle;
            inValue.numero = numero;
            inValue.colonia = colonia;
            inValue.ciudad = ciudad;
            inValue.estado = estado;
            inValue.cp = cp;
            return ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).GenerarFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioResponse test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.GenerarRemisionConPrecio(test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioRequest request) {
            return base.Channel.GenerarRemisionConPrecio(request);
        }
        
        public test_Conexion_PCH.ServicePCH.ctCamposGenerarRemision GenerarRemisionConPrecio(int cliente, string llave, int almacen, string moneda, test_Conexion_PCH.ServicePCH.ctArticuloCantidadPrecio[] articulos, string incluirSeguro, string folioOC) {
            test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioRequest inValue = new test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.almacen = almacen;
            inValue.moneda = moneda;
            inValue.articulos = articulos;
            inValue.incluirSeguro = incluirSeguro;
            inValue.folioOC = folioOC;
            test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioResponse retVal = ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).GenerarRemisionConPrecio(inValue);
            return retVal.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioResponse> test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.GenerarRemisionConPrecioAsync(test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioRequest request) {
            return base.Channel.GenerarRemisionConPrecioAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioResponse> GenerarRemisionConPrecioAsync(int cliente, string llave, int almacen, string moneda, test_Conexion_PCH.ServicePCH.ctArticuloCantidadPrecio[] articulos, string incluirSeguro, string folioOC) {
            test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioRequest inValue = new test_Conexion_PCH.ServicePCH.GenerarRemisionConPrecioRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.almacen = almacen;
            inValue.moneda = moneda;
            inValue.articulos = articulos;
            inValue.incluirSeguro = incluirSeguro;
            inValue.folioOC = folioOC;
            return ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).GenerarRemisionConPrecioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test_Conexion_PCH.ServicePCH.ServicioAprobatorioResponse test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.ServicioAprobatorio(test_Conexion_PCH.ServicePCH.ServicioAprobatorioRequest request) {
            return base.Channel.ServicioAprobatorio(request);
        }
        
        public test_Conexion_PCH.ServicePCH.ctCamposServicioAprobatorio ServicioAprobatorio(int cliente, string llave, test_Conexion_PCH.ServicePCH.ctArticuloPrecio articulo) {
            test_Conexion_PCH.ServicePCH.ServicioAprobatorioRequest inValue = new test_Conexion_PCH.ServicePCH.ServicioAprobatorioRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.articulo = articulo;
            test_Conexion_PCH.ServicePCH.ServicioAprobatorioResponse retVal = ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).ServicioAprobatorio(inValue);
            return retVal.resultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ServicioAprobatorioResponse> test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType.ServicioAprobatorioAsync(test_Conexion_PCH.ServicePCH.ServicioAprobatorioRequest request) {
            return base.Channel.ServicioAprobatorioAsync(request);
        }
        
        public System.Threading.Tasks.Task<test_Conexion_PCH.ServicePCH.ServicioAprobatorioResponse> ServicioAprobatorioAsync(int cliente, string llave, test_Conexion_PCH.ServicePCH.ctArticuloPrecio articulo) {
            test_Conexion_PCH.ServicePCH.ServicioAprobatorioRequest inValue = new test_Conexion_PCH.ServicePCH.ServicioAprobatorioRequest();
            inValue.cliente = cliente;
            inValue.llave = llave;
            inValue.articulo = articulo;
            return ((test_Conexion_PCH.ServicePCH.PCH_MAYOREOPortType)(this)).ServicioAprobatorioAsync(inValue);
        }
    }
}
